language: r
sudo: false
cache: packages
matrix:
  include:
    - os: linux
      dist: precise
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: beta-xcode6.2

r_github_packages:
- hadley/haven
- rdatatable/data.table
r_packages:
- covr
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

before_install: |
  mkdir ~/.R
  cat <<EOF > ~/.R/Makevars
  CXX=g++-4.9
  CXX1X=g++-4.9
  CXX1XSTD=-std=c++11

after_failure:
  email: 
    recipients:
     - thosjleeper@gmail.com
    on_success: change
    on_failure: change
after_success:
  - Rscript -e 'library("covr");codecov()'
